# Ejecutar con: docker-compose up -d 
version: "2"

services:

    entorno1:
        container_name: entorno1
        image:          rastasheep/ubuntu-sshd

    entorno2:
        container_name: entorno2
        image:          rastasheep/ubuntu-sshd
        
    entorno3:
        container_name: entorno3
        image:          rastasheep/ubuntu-sshd
        
    entorno4:
        container_name: entorno4
        image:          rastasheep/ubuntu-sshd
        
    entorno5:
        container_name: entorno5
        image:          rastasheep/ubuntu-sshd