# Esto es lo que llamamos un playbook
# PLAY BOOK: Libro de JUGADAS
# Sabeis que va a contener este fichero? Muchas JUGADAS (Plays)
# Cada play irá represnetado como un item de una lista.
# El playbook va a ser una lista de PLAYs
#- # Play 1
#
#- # Play 2
#---
# En un play definiremos:
# - Las tareas que queremos realizar
# - Los entornos sobre los que realizaremos esas tareas
# - Otros datos, relativos a parametrizaciones con respecto a la forma de ejecutar esas tareas

- # Play 1. El play va a contener un diccionario YAML, con unas claves muy concretas, definidas en el esquema YAML de Ansible
    hosts: localhost # Los entornos sobre los que quiero que se ejecute este play
    
    gather_facts: true # Esta es la primera tarea que se ejecuta siempre...
                       # Siemper claro que no la desactive
                       # Esta tarea QUE SIEMPRE QUERRE DESACTIVAR: SIEMPRE !
                       # No la voy a dejar NUNCA PUESTA POR DEFECTO.
                       # Esta tarea recopila información de la computadora a
                       # la que nos estamos conectando (en nuestro caso localhost)
                       # Es una aberración la cantidad de información que recopila... y lo vemos en un rato
                       # Y para obtenerla tarda un huevo de tiempo... que no me interesa desperdiciar
                       
                       # Cuando se ejecuta un gather_facts, ansible repocila información del entorno destino y almacena toda esa información
                       # dentro de una variable, que tendremos a nuestra disposición en el playbook: `ansible_facts`
                       
    # La división entre PRE, TASKS y POST es a nivel conceptual. FUNCIONALMENTE NO APORTA NADA.
    # Podría meter todas als tareas dentro de uno cualquiera de esos bloques... y todo funcionaría exactamente igual
    # O mejor dicho, podría conseguir que funcionase exactamente igual.
    
    vars: # Aqui metemos un MAPA YAML cuyas claves serán NOMBRES DE VARIABLES
          # Y sus valores, los valores de las variables
        usuario: "felipe"
        home_usuario: "/home/felipe"
    
    pre_tasks: 
        # Aseguramento de Requisitos
        -   # PreTarea 1
            name: Pre Tarea 1
            debug:
                msg: Soy la pretarea 1 # Esto es un texto según YAML
                                       # Qué va a hacer Ansible con la mayoría de los textos
                                       # que escribimos en los playbooks.
                                       # En cuanto ansible lee uno de esos textos, lo pasa por JINJA !
                                       # Según Ansible, son plantillas JINJA
        -   # PreTarea 2
            name: Pre Tarea 2
            debug:
                msg: Soy la pretarea 2 # Esto es una plantilla JINJA 

        -   # PreTarea 3
            name: Pre Tarea 3
            debug:
               # msg: "{{ ansible_facts }}"
                var: ansible_facts # En este caso, en la docu del modulo debug, ya me indican que ellos pondrán las dobles llaves
    
        -   # PreTarea 4
            name: Pre Tarea 4
            debug:
                msg: "Sistema operativo: {{ ansible_facts.distribution }}" # En las plantillas JINJA podemos hacer uso de variables, encerrando el nombre de la variable entre dobles llaves
    
        -   # PreTarea 5
            name: Pre Tarea 5
            debug:
                # Como estamos viendo, entre las llaves lo que ponemos es una expresión
                # Una expresion puede ser una variable
                msg: "Memoria swap libre: {{ ansible_facts.memory_mb.swap.free }}" 
    
        -   # PreTarea 6
            name: Pre Tarea 6
            debug:
                msg: "Tipo del 2º CPU: {{ ansible_facts.processor[5] }}"

        -   # PreTarea 7
            name: Pre Tarea 7
            debug:
                # Una expresion puede ser un calculo, usando operadores: + - / * > < >= <= == != and or not
                msg: |-
                    Un calculo: {{ 3 + 4 }}
                    Memoria en uso: {{ ansible_facts.memory_mb.real.total - ansible_facts.memory_mb.real.free }}
                    
        -   # PreTarea 8
            name: Pre Tarea 8
            debug:
                # Una expresión JINJA también puede hacer uso de FILTROS JINJA 
                # Un filtro JINJA es una función que aplicamos sobre un valor...
                # Sería algo así (en su sintaxis) como los PIPES de linux / unix
                msg: "Tipo del 2º CPU: {{ ansible_facts.processor[5] | upper }}"
                # Tenemos un huevo de filtro definidos en JINJA de forma pedeterminada:
                # https://jinja.palletsprojects.com/en/3.1.x/templates/#list-of-builtin-filters
                # Además de esos filtros, ANSIBLE aporta sus propios filtros JINJA:
                # https://docs.ansible.com/ansible/2.8/user_guide/playbooks_filters.html
    
    tasks: # Aqui dentro tendré una LISTA YAML, donde cada item representará una TAREA
           # Las tareas aquí definidas las iremos ejecutando de forma secuencial.
           # Una tarea solo se ejecutará si las anteriores no han fallado (a priori)
           # Dicho de otra forma: Si una tarea falla, el playbook se detiene sobre el entorno que lo
           # estemos ejecutando... quizas el playbook lo estoy ejecutando sobre 20 entornos... y en 19 va bien
        -   # Tarea 1: Cada tarea tendrá: Un NOMBRE, Un MODULO (con una configuración)
            name: Tarea 1
            debug:
                msg: Soy la tarea 1

        ##########################################################################################
        #   Control del estado de ejecución de una tarea
        #   Hemos dicho que una tarea puede acabar en estado: OK, CHANGED, FAILED
        #   Cómo decide Ansible el estado de finalización de una tarea?         ANSIBLE NO LO DECIDE
        #   Quién lo decide? Quién es conocedor de esa información?             El MODULO, que es quien lo ejecuta
        #   Cada modulo informa a Ansible de si la tarea ha ido bien, de si ha provocado cambios, o de si ha ido mal
        #   No todo modulo tiene la información de si lo que ha ejecutado ha ido bien o mal o ha provocado cambios
        #   ^^^ PROBLEMA !
        ##########################################################################################
        -   # Tarea 2
            name: Tarea 2
            debug:
                msg: Soy la tarea 2
            # Más cosas que podemos añadir en una tarea        
        
        -   # Tarea 3
            name: Asegurarme que hay un usuario 'felipe' con una configuración. 
                # Y no me cuentes tu vida Ansible, que es muy triste... Me la pela como lo hagas... SOLO HAZLO !
            user:
                name: "{{ usuario }}"
                home: "{{ home_usuario }}"
                state: present
            # Ponerme como administrador... equivalente al sudo
            become: true
            # Este MODULO, me respeta el principio de IDEMPOTENCIA:
                # Si no está el usuario, que hará? CREARLO
                # Si está el usuario, que hará?    NADA
                # Si existe el usuario pero con otro home? Modificarle el home
            # Os dije que los módulos (el 99.9% de ellos) nos dan IDEMPOTENCIA

        -   # Tarea 4
            name: Quiero saber la versión de nginx que tengo instalada
            shell:
                cmd: nginx --version
            # Y por defecto el módulo shell siempre devuelve que aquello ha provocado cambio
            # Ya que no tiene forma de saber si realmente ha provocado cambio o no
            # Y en este caso es MI RESPONSABILIDAD informar del estado resultante
            # El modulo shell es de ese 0.01% de modulos que no ofrecen IDEMPOTENCIA!
            changed_when: false
            failed_when:  false # Aqui podemos poner expresiones JINJA !
        ##########################################################################################
        # Control del flujo: Condicionales
        ##########################################################################################
        -   # Tarea 5
            name: Tarea 5
            debug:
                msg: Soy una tarea condicional... que se ejecuta solo en máquinas UBUNTU !
            when: ansible_facts.distribution == "Ubuntu" # Expresion lógica jinja (es decir, que devuelva true o false)... sin llaves

        -   # Tarea 6
            name: Tarea 6
            debug:
                msg: Soy una tarea condicional... que se ejecuta solo en máquinas QUE NO SEAN UBUNTU !
            when: ansible_facts.distribution != "Ubuntu" # Expresion lógica jinja (es decir, que devuelva true o false)... sin llaves
        ##########################################################################################
        # Control del flujo: TAGS
        # Los tags me permiten determinar al lanzar la ejecución del playbook,
        # Que tareas quiero o no quiero que se ejecuten:
        # Al llamar a ansible-playbook 2 argumentos:
        #   --tags Que me permite determinar los tags que quiero que se ejecuten
        #   --skip-tags Que me permite determinar los tags que no quiero que se ejecuten
        # SIEMPRE PONEMOS TAGS en todas las tareas:
        # instalacion, pruebas, configuracion, requisitos
        ##########################################################################################
        -   # Tarea 7
            name: Tarea 7
            debug:
                msg: Esta es una tarea que está instalando unas cosas 
            tags:
                - instalacion

        -   # Tarea 8
            name: Tarea 8
            debug:
                msg: Esta es una tarea que está configurando unas cosas
            tags:
                - configuracion

        -   # Tarea 9
            name: Tarea 9
            debug:
                msg: Esta es una tarea que está probando unas cosas
            tags:
                - test
                - always # Este es un tag propio de ansible... y las tareas con este tag se ejecutan siempre
                # - never # Es lo contrario a always. En mi puñetera vida he entendido para que sirve
        ##########################################################################################
        # Control del flujo: HANDLERS
        # Los handlers son tareas que se ejecutan solo cuando SON INVOCADOS
        # Cuando un handler es invocado:
        # - que una tarea (pre, tasks, post) defina la propiedad notify apuntando a un handler
        # - la tarea con el notify, al ejecutarse, debe provocar un cambio (CHANGED)
        # Con independencia de cuando un handler es invocado,
        # Los handlers que hayan sido invocados se ejecutan al finalizar el bloque 
        # (pre, tasks, post) en el que han sido invocados.... Y SOLO UNA VEZ
        # aunque hayan sido invocados varias veces
        # MALA PRACTICA Es poner en un notify el nombre de una tarea HANDLER
        # BUENA PRACTICA, una tarea notifica UN EVENTO!
        #                 nuestros handlers escucharán eventos
        ##########################################################################################

        -   # Tarea 10
            name: Tarea 10
            debug:
                msg: Esta es una tarea que va a invocar un handler
            notify: 
                - Handler 1  # MALA PRACTICA
                - Handler 1.2
            changed_when: true

        -   # Tarea 11
            name: Tarea 11
            debug:
                msg: Esta es una tarea quetambién va a invocar un handler
            notify: 
                - Handler 1  # MALA PRACTICA
                - Handler 1.2
            changed_when: true

        -   # Tarea 12
            name: Tarea 12
            debug:
                msg: Esta es otra tarea
                
        -   # Tarea 14
            name: Tarea 14
            debug:
                msg: Esta es una tarea que invoca un EVENTO 
            notify: SERVIDOR_RECONFIGURADO  # BUENA PRACTICA
            changed_when: true
      
        -   # Tarea 15
            name: Tarea 15
            debug:
                msg: Esta es una tarea que invoca un EVENTO 
            notify: SERVIDOR_RECONFIGURADO  # BUENA PRACTICA
            changed_when: true

    post_tasks:
        #   Pruebas / Validaciones
        #   Notificaciones
        -   # Post Tarea 1
            name: Post Tarea 1
            debug:
                msg: Soy la posttarea 1
        -   # Post Tarea 2
            name: Post Tarea 2
            debug:
                msg: Soy la posttarea 2

        -   name: Conjunto de tareas relacionadas
            block: # try
                -   # Tarea 1 del bloque
                    name: Tarea 1 del bloque
                    debug:
                        msg: Soy la Tarea 1 del bloque
                    failed_when: true
                -   # Tarea 2 del bloque
                    name: Tarea 2 del bloque
                    debug:
                        msg: Soy la Tarea 2 del bloque
            rescue: # catch|except
                # Las tareas del bloque rescue se ejecutan SOLO
                # si alguna tarea del bloque principal da error,
                # dandome la oportunidad de gestionar ese error
                -   # Tarea 1 del rescue
                    name: Tarea 1 del rescue
                    debug:
                        msg: Soy la Tarea 1 del rescue
                -   # Tarea 2 del rescue
                    name: Tarea 2 del rescue
                    debug:
                        msg: Soy la Tarea 2 del rescue
            always: # finally
                # Estas tareas se ejecutan tanto si las tareas del bloque van bien, como si van mal
                -   # Tarea 1 del always
                    name: Tarea 1 del always
                    debug:
                        msg: Soy la Tarea 1 del always
            #tags: # Que aplican a cada tarea del bloque
            #when: # Que aplican a cada tarea del bloque

        -   # Post Tarea 3
            name: Post Tarea 3
            debug:
                msg: Soy la posttarea 3
            failed_when: true    
            ignore_errors: true
            
        -   # Post Tarea 4
            name: Post Tarea 4
            debug:
                msg: Soy la posttarea 4
                
                

        -   # Post Tarea 5
            name: Quiero saber la versión de ansible que tengo instalada
            shell:
                cmd: ansible --version
            # Y por defecto el módulo shell siempre devuelve que aquello ha provocado cambio
            # Ya que no tiene forma de saber si realmente ha provocado cambio o no
            # Y en este caso es MI RESPONSABILIDAD informar del estado resultante
            # El modulo shell es de ese 0.01% de modulos que no ofrecen IDEMPOTENCIA!
            changed_when: false
            failed_when:  false # Aqui podemos poner expresiones JINJA !
            register: version_ansible # Esta variable guarda la salida del MODULO
                
        -   # Post Tarea 6
            name: Mostrar la versión que tengo de Ansible
            debug:
                msg: |
                    La version de ansible es: {{ version_ansible.stdout }}
                    La version de ansible es: {{ version_ansible.stdout_lines[0] }}
                    Return code: {{ version_ansible.rc }}
        -   # Post Tarea 7
            name: Ansible no está instalado
            debug:
                msg: Ansible no está instalado
            when: version_ansible.rc > 0
            
                
        -   # Post Tarea 8
            name: Quiero saber la versión de ansible que tengo instalada
            shell:
                cmd: nginx --version
            # Y por defecto el módulo shell siempre devuelve que aquello ha provocado cambio
            # Ya que no tiene forma de saber si realmente ha provocado cambio o no
            # Y en este caso es MI RESPONSABILIDAD informar del estado resultante
            # El modulo shell es de ese 0.01% de modulos que no ofrecen IDEMPOTENCIA!
            changed_when: false
            failed_when:  false # Aqui podemos poner expresiones JINJA !
            register: version_nginx
            
        -   # Post Tarea 9
            name: Nginx no está instalado
            debug:
                msg: Nginx no está instalado
            when: version_nginx.rc > 0
        
        -   name: Comprobar disponibilidad de nginx
            block:
                - name: comprobar la version instalada de nginx
                  shell:
                    cmd: nginx --version
            rescue:
                - name: Nginx no está instalado
                  debug:
                    msg: Nginx no está instalado
            
            # A las variables que generamos con un register, podemos preguntarles:
            #.  is skipped
            #.  is failed
            #.  is success
            #.  is changed
               
        -   # Post Tarea 8
            name: Quiero saber la versión de ansible que tengo instalada
            shell:
                cmd: nginx --version
            changed_when: false
            register: version_nginx_2
            ignore_errors: true
            
        -   # Post Tarea 9
            name: Nginx no está instalado
            debug:
                msg: Nginx no está instalado
            when: version_nginx_2 is failed
            
        -   debug:
                var: version_nginx_2
                
        -   # Post Tarea 8
            name: Quiero saber la versión que tengo instalada de unos programas
            shell:
                cmd: "{{ item }} --version"
            changed_when: false
            failed_when: false
            loop:
                - ansible
                - nginx
                - curl
            register: versiones
                
        -   debug:
                var: versiones
                
        -   debug:
                msg: "La version instalada del programna: {{ ???? }} es: {{ ???? }}"
            when: ???
            loop: ???
            # Si es que ese programa está instalado
            
    handlers:
        -   # Handler 1
            name: Handler 1
            debug:
                msg: Soy el Handler 1
        -   # Handler 1.2
            name: Handler 1.2
            debug:
                msg: Soy el Handler 1.2
                
                
                
        -   # Handler 2
            name: Handler 2
            debug:
                msg: Soy el Handler 2
            listen:
                - SERVIDOR_RECONFIGURADO
        -   # Handler 3
            name: Handler 3
            debug:
                msg: Soy el Handler 3
            listen:
                - SERVIDOR_RECONFIGURADO
        -   # Handler 3.1
            name: Handler 3.1
            debug:
                msg: Soy el Handler 3.1
            listen:
                - SERVIDOR_RECONFIGURADO
                